ports:
  - port: 8000
    onOpen: open-preview
  # xdebug port
  - port: 9003
    onOpen: ignore

# Commenting out. We'll run these manually in class.
tasks:
  - init: echo "Getting started!"
    command: php -S localhost:8000

vscode:
  extensions:
    # PHP extensions.
    - felixfbecker.php-debug
    - wongjn.php-sniffer
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    # Twig extensions.
    - mblode.twig-language-2
